### ISSUE TITLE
Custom Components

### ISSUE THREAD

**Issue by PurpleNecho** [wix-incubator/mjml-react#18]
Is there a way to add custom MJML components or are you planning on adding this feature?

**Comment by mastertheblaster** [comment]
Hi @PurpleNecho,

Currently we don't see a reason to add support for this.
IMHO it can be achieved by composing existing react components.

```js
class MyFancyButton {
  render() {
     return [
       <MjmlRaw>
         <p>Some raw component</p>
       </MjmlRaw>
       <MjmlSection>
         <MjmlColumn>...</MjmlColumn>
         <MjmlColumn>...</MjmlColumn>
       </MjmlSection>
     ];
  }
}
```

Can you share your usecase? And maybe we would change our mind :) And on the other hand - we do accept PRs :)

**Comment by PurpleNecho** [comment]
Thanks for the quick answer.
A usecase would be a button component with conditional comments and VML for older Outlook versions in which case it would be quite tedious to repeat the component for every instance of that button.

**Comment by mastertheblaster** [comment]
Hi @PurpleNecho,

Could you share a code snippet of such button? 
Maybe there are other alternatives also, but you are right `MjmlRaw` can do anything.

Cheers

**Comment by mastertheblaster** [comment]
Closing for now, please feel free to reopen if needed.

Cheers
