### ISSUE TITLE
[Proposal] Add PropTypes with all mjml attributes

### ISSUE THREAD

**Issue by dariuszpaluch** [wix-incubator/mjml-react#26]
Maybe we add __React PropTypes__ to __MjmlComponents__ with all attributes, validate correct unit and description from mjml documentation.

It's very useful when working with Mjml Components in well IDE such as CodeStudio, Webstorm
Then editor show available props, require props, default values .etc

I can create some PR with this future.

**Comment by mastertheblaster** [comment]
Thanks for the proposal. Sounds promising.
It would be awesome if you could make a small PR for a single component and a single property.

**Comment by kranux** [comment]
Hey @dariuszpaluch any updates? :)

Cheers!
