### ISSUE TITLE
Very confused about version system

### ISSUE THREAD

**Issue by callumlocke** [wix-incubator/mjml-react#28]
Hi! We have recently started using MJML and mjml-react, and they are really useful so far, thanks for making them. But in trying to debug a build problem (which may or may not involve mjml-react), I am stuck because I can't figure out your versioning system at all.

- The most recent published version [on npm](https://www.npmjs.com/package/mjml-react), is `1.0.55`.
- The [package.json version in `master`](https://github.com/wix-incubator/mjml-react/blob/master/package.json) is `1.0.0`.
- The latest tag is something called `dummy` (?), also at `1.0.0`, and seems to be pretty much the same as `master`.
- Other [releases](https://github.com/wix-incubator/mjml-react/releases)/tags have names like `RC;.;1.30.0`, which I guess are release candidates? They seem to have higher version numbers than anything yet released to npm, but they seem to be [behind](https://github.com/wix-incubator/mjml-react/compare/RC;.;1.30.0...master) master?
- I can't find any changelog or release notes anywhere. And without git tags or even changes to the `package.json` version string, I can't see any reasonable way to work out for myself what the difference is between `1.0.54` and `1.0.55`, for example.

Can someone shed some light?

**Comment by kranux** [comment]
Hi,

`mjml-react` library is build using our internal build tool. Basically every commit to master is new minor version of npm package.

Npm package versions are listed here: https://www.npmjs.com/package/mjml-react
Pushes to master are listed here: https://github.com/wix-incubator/mjml-react/commits/master
