### ISSUE TITLE
Update mjml to latest version

### ISSUE THREAD

**Issue by rfoel** [wix-incubator/mjml-react#33]
There were a few changes since v4.1.2 of mjml. Will it be updated anytime?

**Comment by mattcasey** [comment]
The version used by this library is "^4.1.2" which means that when you install it, npm will grab the latest 4.x version. If you have a package-lock.json file, try `npm install mjml-react@latest` to grab the latest depedencies.

**Comment by rfoel** [comment]
Thanks
