### ISSUE TITLE
Media queries

### ISSUE THREAD

**Issue by Emiliano-Bucci** [wix-incubator/mjml-react#34]
Hi! I'm having issues with media queries, specifically in my Gmail App (i have a Huawei with Android 8). It seems that they're completely ignored; i've tried using both styles in the head inlined and not, but with no result at all. Perhaps did you face some similar issues?

I've also noticed that if i use the inline attribute in the <MjmlStyle /> the media queries are not being applied anymore

Thanks a lot!

**Comment by daliusd** [comment]
Hey, I recommend checking Google documentation about media queries support in Gmail:

* https://developers.google.com/gmail/design/css

* https://developers.google.com/gmail/design/reference/supported_css
