### ISSUE TITLE
Integration with create-react-app?

### ISSUE THREAD

**Issue by mrlubos** [wix-incubator/mjml-react#37]
Hey! Thanks for making this wrapper for React. I am wondering what's the best way to integrate this project with create-react-app? It appears it already has all dependencies this project uses, maybe except for `express`.

**Comment by mastertheblaster** [comment]
Hi @mrlubos,

`mjml-react` library is designed to be run on a server side only (at least currently).
It won't run in a browser app created by `create-react-app`, unless you would use server side rendering only.

**Comment by mrlubos** [comment]
Hi @mastertheblaster! That makes sense. Are you able to point me to where this server-side limitation comes from and what would be needed to get it working in browser? Is it the `mjml` package directly?

**Comment by mastertheblaster** [comment]
Hey @mrlubos you can check the following links:

https://github.com/wix-incubator/mjml-react/issues/36#issuecomment-646930723
https://github.com/mjmlio/mjml/issues/1365

Suma sumarum you are right, it's the limitation of the `mjml` package. Check the second link above.

**Comment by mrlubos** [comment]
Thank you for your help @mastertheblaster!

**Comment by mrlubos** [comment]
@mastertheblaster Can we reopen this issue now that [`mjml-browser`](https://github.com/mjmlio/mjml/releases/tag/v4.8.0) package is available?

**Comment by mrlubos** [comment]
Hey @mastertheblaster, there's now the great mailing project which implements this functionality and builds on top of this project and mjml! https://github.com/successor-software/mailing
