### ISSUE TITLE
Component children for conditional comments

### ISSUE THREAD

**Issue by jonwalz** [wix-incubator/mjml-react#39]
Hello and great work you all have done on this library.

I am working on managing dark mode in my emails and wondering if there is a way to have components as children to the `MjmlConditionalComment` component? Babel tells me it must be a string.

My work around is as follows but also is not working correctly because the child div is not generated in the output html.

```
      <MjmlColumn padding="0 2% 0 0" width="73%" vertical-align="middle">
        <MjmlComment>{`[if !mso]><! `}</MjmlComment>
        <div
          css-class="dark-img"
          align="center"
          style={{
            display: "none",
            overflow: "hidden",
            float: "left",
            width: "0px",
            maxHeight: "0px",
            maxWidth: "0px",
            lineHeight: "0px",
            visibility: "hidden",
          }}
        >
          <MjmlImage
            src="http://...image.png"
            width="124px"
            align="left"
            padding-left="0"
          />
        </div>
        <MjmlComment>{`<![endif]`}</MjmlComment>
      </MjmlColumn>
```

I am following suggestions made in this article for handling dark mode: https://www.litmus.com/blog/the-ultimate-guide-to-dark-mode-for-email-marketers/

Any advice is greatly appreciated and thank you.

**Comment by daliusd** [comment]
Your workaround is good. `MjmlConditionalComment` will not work in your situation. You need to wrap `div` into `MjmlRaw` (see https://mjml.io/documentation/#mj-raw). I hope that will solve your problem.

**Comment by daliusd** [comment]
I'm closing this issue as there is not feedback from reporter. Feel free to reopen this issue or ask more questions.
