### ISSUE TITLE
Error: Cannot find module '../lib/utils.js'

### ISSUE THREAD

**Issue by codyng** [wix-incubator/mjml-react#42]
Used with create-react-app, when import stuff from 'mjml-react', it causes the error:
Error: Cannot find module '../lib/utils.js'

Any idea?

![Screenshot 2020-10-23 at 18 19 36](https://user-images.githubusercontent.com/4618641/96992381-67591d00-155c-11eb-98f9-7f5e6ce457da.png)

**Comment by mastertheblaster** [comment]
Hey @codyng,

This library is meant to be run inside `node`, not in the browser. https://github.com/wix-incubator/mjml-react#limitations
It's the limitation of underlying original `mjml` library.

Regards

**Comment by mastertheblaster** [comment]
Closing this issue as we cannot do anything about it. Please feel free to reopen if you think it can be fixed.
