### ISSUE TITLE
<MjmlStyle> doesn't render any styles inside of <MjmlHead>

### ISSUE THREAD

**Issue by swifttarrow** [wix-incubator/mjml-react#44]
Hi there! First time raising an issue here, so apologies if the format isn't correct.

I'm trying to render css classes in my html head. Eventually, I want to render media queries there and apply them to my MjmlText components. But I'm not able to render anything in head.

Simple repro:
```
<Mjml>
  <MjmlHead>
    <MjmlStyle inline>
      ` .red { color: red; }`
    </MjmlStyle>
  </MjmlHead>
</Mjml>
```
When I go examine the rendered html in dev tools, I see other css classes (probably ones created by mjml) in the head attribute, but not the one I created.

**Comment by mastertheblaster** [comment]
Hey @swifttarrow,

Please remove the property `inline`. It's a little bit tricky.
`inline` property tells to inline all the css you declare in this block directly on your elements (buttons, texts, links, etc).
More information can be found here: https://documentation.mjml.io/#mj-style

```tsx
<MjmlStyle inline>
  .red { color: red }
</MjmlStyle>
...
<MjmlText cssClass="red">...</MjmlText>
```

Will result in a such pseudo code (and no style tag will be emitted to final output):

```tsx
<div style="color:red">...</div>
```

Regards,
Mantas

**Comment by mastertheblaster** [comment]
You can go to this online playground https://mjml.io/try-it-live
And paste the following code:

```html
<mjml>
  <mj-head>
    <mj-style>
      .blue div {
        color: blue!important;
      }
      @media only screen and (min-width:480px) {
        .blue div {
          color: pink!important;
        }
      }
    </mj-style>
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text font-size="20px" font-family="helvetica" css-class="blue">Hello World</mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
```

**Comment by mastertheblaster** [comment]
As the feature works as designed, I am closing the issue. Please feel free to reopen if needed.
