### ISSUE TITLE
Missing mjml components

### ISSUE THREAD

**Issue by dbullerwell** [wix-incubator/mjml-react#5]
The below standard mjml elements are missing

- mjml-accordion
- mjml-accordion-element
- mjml-accordion-text
- mjml-accordion-title
- mjml-carousel
- mjml-carousel-image
- mjml-group
- mjml-navbar
- mjml-navbar-link
- mjml-social
- mjml-social-element
- mjml-table

I've got a local branch with the elements already created, and I'd be happy to push that for a pull request if you'd like.

**Comment by mastertheblaster** [comment]
Hi @dbullerwell you are very welcome to make a PR.

**Comment by mastertheblaster** [comment]
Thanks @dbullerwell, merged and published a new version `1.0.23`

**Comment by mastertheblaster** [comment]
#6 merged so closing the issue
