### ISSUE TITLE
Add `mj-include` component

### ISSUE THREAD

**Issue by IanEdington** [wix-incubator/mjml-react#53]
Hey this is a pretty simple ask.

We are in the process of migrating from mjml to mjml-react.

We're planning on doing it slowly over the next couple months and would need a mj-include tag in order for it to work properly.

Is there any reason this wasn't included in the library?

**Comment by IanEdington** [comment]
I ran into some issues with relative paths and ended up defining `filePath` directly in the mjml options.

If there's interest I can put up a PR

**Comment by daliusd** [comment]
PRs are always welcome.

**Comment by daliusd** [comment]
As this project is not maintained anymore and nothing happened with this issue I am closing it.
