### ISSUE TITLE
`minify` option is deprecated

### ISSUE THREAD

**Issue by Pedro-Souza** [wix-incubator/mjml-react#58]
The `minify` option is depreciated and when used a warning is triggered(see image). To solve it we could just remove the [minify](https://github.com/wix-incubator/mjml-react/blob/master/src/index.js#L46), what do you think?

PR that removed the minify option: https://github.com/mjmlio/mjml/pull/2059

![image](https://user-images.githubusercontent.com/10675595/115165431-46453500-a084-11eb-8069-c38aa53c2f41.png)

**Comment by botre** [comment]
You can toggle of the option explicitly:

```javascript
const { html, errors } = render(email, {
  minify: false
});
```

Since this option is deprecated, I agree that the default should be false.

**Comment by andreymoser** [comment]
I resolved using the same dependency (`html-minifier`) and minfy handling from `mjml-core` as the following:

```js
htmlMinify(html, {
  collapseWhitespace: true,
  minifyCSS: false,
  caseSensitive: true,
  removeEmptyAttributes: true,
})
````

I hope it helps, one good thing is to move this handling into `mjml-react`. :)

**Comment by daliusd** [comment]
PRs are welcome

**Comment by pkuczynski** [comment]
Here you go @daliusd #75. I couldn't run it locally as `@wix/yoshi` does not seem to exist anymore?

**Comment by daliusd** [comment]
Yes, it does not work locally anymoree.

**Comment by pkuczynski** [comment]
> Yes, it does not work locally anymore.

Shall this be fixed?

**Comment by daliusd** [comment]
> > Yes, it does not work locally anymore.
> 
> Shall this be fixed?

It is complicated. We would need to drop `@wix/yoshi` to fix this.

**Comment by pkuczynski** [comment]
I know its complicated, but maybe worth it, if this package is not public?

**Comment by daliusd** [comment]
> I know its complicated, but maybe worth it, if this package is not public?

It was public and is not public anymore. Most probably we will do something about it but we have other pressing problems to solve now and time will come to this problem as well eventually.
