### ISSUE TITLE
Support for Table?

### ISSUE THREAD

**Issue by libasoles** [wix-incubator/mjml-react#7]
Great iniciative. 
See, the lib is missing the Table component.
So, I'm trying to fill the gap, like this:

```
class MjmlTable extends Component {
  render() {
    const { children, ...rest } = this.props;
    return React.createElement('mj-table', handleMjmlProps(rest), children);
  }
}
```

However, this ends up rendering `children` as mjml tags instead of html tags. See:
```
<td style="font-size:16px;padding:4px;padding-top:8px;padding-bottom:8px;word-break:break-word">
<mj-text align="left" color="#1e2c3e" font-size="16px" line-height="22px" padding-top="8px" padding-bottom="8px">Coffe x2</mj-text>
</td>
```

Any clue on how to solve it?

**Comment by mastertheblaster** [comment]
Based per original `mjml` documentation, table allows only plain HTML:
https://mjml.io/documentation/#mjml-table

> This tag allows you to display table and filled it with data. It only accepts plain HTML.

In your case IMHO it would be enough to have:

```js
<MjmlTable>
  <tr>
    <!-- spacings at table cell level -->
    <td style="padding:8px 4px;word-break:break-word">
      <span style="font-size:16px;line-height:22px;color:#1e2c3e;">Foo Bar</span>
    </td>
  </tr>
</MjmlTable>
```

**Comment by libasoles** [comment]
Great catch. Thank you.
