### ISSUE TITLE
Support for mj-html-attributes, mj-selector, mj-html-attribute?

### ISSUE THREAD

**Issue by philipwindeyer** [wix-incubator/mjml-react#71]
Hello, is there a timeline on adding support for the newer `mj-html-attributes`, `mj-selector`, and `mj-html-attribute` head components?

I.e. https://documentation.mjml.io/#mj-html-attributes

Thanks in advance

**Comment by philipwindeyer** [comment]
Saw that; although it's a year old and it's attempting to redefine `MjmlAttributes` as `MjmlHtmlAttribute` 😕.

I can dedicate time to this on Monday. Will open a new PR then if that works for you? @daliusd

**Comment by daliusd** [comment]
Yes, it works for me.

**Comment by philipwindeyer** [comment]
Hey @daliusd, just opened https://github.com/wix-incubator/mjml-react/pull/72 . Will update types in DefinitelyTyped shortly

**Comment by daliusd** [comment]
Hi @philipwindeyer we will review it.

**Comment by philipwindeyer** [comment]
FYI: PR for accompanying typedefs, for the TypeScripters https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59026
