### ISSUE TITLE
Support for templating fields within style attributes

### ISSUE THREAD

**Issue by nick-avi-say** [wix-incubator/mjml-react#73]
Hi, currently when using variables in fields. The render method strips out the value.  Tried setting validation to skip, and that alleviates the error thrown, but the string `"{{myVariable}}"` is still stripped

`<MjmlBody backgroundColor="{{myVariable}}">`

**Comment by nick-avi-say** [comment]
PR created here https://github.com/wix-incubator/mjml-react/pull/74

**Comment by daliusd** [comment]
This project is not maintained anymore so there will be no fix proposal.
