### ISSUE TITLE
Package dependencies with mjml-react

### ISSUE THREAD

**Issue by psugihara** [wix-incubator/mjml-react#78]
Quick question I hope. What's the reason that `mjml-react` requires you to install extra dependencies with it? Can they be included in `mjml-react`?

It would be simpler for users to `npm install mjml-react` rather than `npm install react react-dom mjml mjml-react`. I know it's tripped up a few people (#69 👋).

I'm sure this has been considered, so I wanted to understand the reasoning/limitation.

Thanks, this is a great lib!

**Comment by daliusd** [comment]
We can't bind to specific version as user might be forced to use specific version in their situation.

**Comment by psugihara** [comment]
Got it, thanks!
