### ISSUE TITLE
<Mjml>     ^ SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by apurvjain28** [wix-incubator/mjml-react#85]
<img width="552" alt="Screen Shot 2022-07-19 at 11 06 49 AM" src="https://user-images.githubusercontent.com/54246887/179784264-33d76d9f-5339-408a-81e1-4065a0983395.png">

I have been trying to replicate the same example as given in the link below in my project: 
https://github.com/wix-incubator/mjml-react-example/blob/master/src/email.js

But it is showing a weird Syntax Error as if it doesn't understand mjml-react syntax. If I try to send normal mjml rendered HTML on my mailTrap account then it's working. But somehow it can not read the imports from mjml-react. 

What could be the possible fix for it?

**Comment by daliusd** [comment]
It looks like you have not configured react properly.
