### ISSUE TITLE
MjmlRaw not showing <p> tags

### ISSUE THREAD

**Issue by toto1384** [wix-incubator/mjml-react#88]
So I want to use the paragraph tag inside the mjml raw tag, but it's not showing. I've tried setting defined width and hide but with no success

Code:
`<MjmlRaw><p>ksdnvlksdf</p></MjmlRaw>`

This is the result i've got
<img width="216" alt="Screenshot 2022-08-29 at 16 43 08" src="https://user-images.githubusercontent.com/35605914/187215285-83e85830-29f4-4310-b8d0-c087c33123c0.png">

**Comment by daliusd** [comment]
This project is not maintained anymore.

I would look into generated HTML - screenshot might not say the whole story.
