### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by bytewiz** [wix-incubator/mjml-react#9]
hi there, is this planning on being maintained?

**Comment by mastertheblaster** [comment]
@bytewiz Yes, it's maintained. Do you have some feature request?

**Comment by bytewiz** [comment]
@mastertheblaster Thanks for the quick reply and not currently, I were just looking for something similar to this as I am planning building an email builder based on mjml but I wish to create it using react. At least I would be happy to contribute to the project! :v:

**Comment by mastertheblaster** [comment]
Pull requests are welcome. And meanwhile closing this issue and waiting for PRs :)
