### ISSUE TITLE
Why the project not more maintained?

### ISSUE THREAD

**Issue by ale-grosselle** [wix-incubator/mjml-react#90]
Hello, very sad to read this notice, but of course we have to acept It!

Is possible to know the motivations? 
The library does not fit your goals?
Do you find some problems and you decide to change Road?
The answer could help me a lot, many many thanks

**Comment by daliusd** [comment]
Hey, sorry for late response. The situation is that we don't use `mjml-react` here at Wix anymore and don't have resources to do that properly and with proper dedication. What I can say already that one or more forks will pop up and at least I personally will give some time for that.

Yes, library does not fit our goals, but it is still really good library IMHO. The limitation that hit us is that `mjml` does not allow partial rendering (e.g. https://github.com/mjmlio/mjml/issues/157, but there are more similar issues). This shouldn't be a problem for many old time or new users.
