### ISSUE TITLE
React 18 and react-reconciler 0.27

### ISSUE THREAD

**Issue by florian-milky** [wix-incubator/mjml-react#95]
To be used with react 18 and have correct dependencies, this library needs to use at least `react-reconciler` 0.27
See [the relevant update there](https://github.com/facebook/react/commit/34aa5cfe0d9b6ec4667e02bf46ab34d83dfb2d6d#diff-2d14195873b26f1f3f28556d1be47431615445ecc5670c07cd83d9c75f9ca1b9)

**Comment by daliusd** [comment]
This project is not maintained anymore. Check README for alternative branches.

**Comment by florian-milky** [comment]
sorry yeah this was meant for the fork

**Comment by daliusd** [comment]
no problem ;)
